/**
 * Review bridge injected into a prototype document.
 *
 * Comment mode and pin badges must run inside the prototype, not on a glass
 * overlay: the overlay maps coordinates across two documents and a CSS scale,
 * which is why pins drift. This script listens on the real document, paints a
 * highlight on event.target, draws numbered pins from the host's comment list,
 * and postMessages picks / pin clicks back to the app.
 *
 * Pattern copied from web-internal-tools lib/prototype-bridge.ts and
 * prototype-export-review.ts.
 */

import type { CommentPin, PinPlacement } from '../types';

export const REVIEW_MODE_MESSAGE = 'review-mode';
export const REVIEW_PICK_MESSAGE = 'review-pick';
export const REVIEW_CANCEL_MESSAGE = 'review-cancel';
export const REVIEW_WHEEL_MESSAGE = 'review-wheel';
export const REVIEW_PINS_MESSAGE = 'review-pins';
export const REVIEW_SELECT_MESSAGE = 'review-select';
export const REVIEW_OPEN_PIN_MESSAGE = 'review-open-pin';
export const REVIEW_PIN_LOCATE_MESSAGE = 'review-pin-locate';
/** Bump when the injected script changes so srcDoc iframes reload. */
export const REVIEW_BRIDGE_VERSION = 3;

export type ReviewPickTarget = {
  selector: string;
  describe: string;
  text: string;
  anchorX: number;
  anchorY: number;
  xPercent: number;
  yPercent: number;
};

export type ReviewPinTone = 'resolved' | 'critical' | 'high' | 'default';

export type ReviewPinMarker = {
  id: string;
  label: string;
  selector?: string;
  text?: string;
  anchorX?: number;
  anchorY?: number;
  xPercent: number;
  yPercent: number;
  selected?: boolean;
  pending?: boolean;
  tone?: ReviewPinTone;
  author?: string;
  body?: string;
  category?: string;
  status?: string;
};

const BRIDGE_ATTR = 'data-review-bridge';

/**
 * Written as an array of lines so a `</script>` sequence never appears in the
 * TypeScript template that holds this, and so the HTML parser never sees one
 * inside the injected IIFE.
 */
const REVIEW_SCRIPT = [
  '(function () {',
  "  if (window.__reviewBridgeInstalled) { return; }",
  '  window.__reviewBridgeInstalled = true;',
  '',
  `  var MODE = '${REVIEW_MODE_MESSAGE}';`,
  `  var PICK = '${REVIEW_PICK_MESSAGE}';`,
  `  var CANCEL = '${REVIEW_CANCEL_MESSAGE}';`,
  `  var WHEEL = '${REVIEW_WHEEL_MESSAGE}';`,
  `  var PINS = '${REVIEW_PINS_MESSAGE}';`,
  `  var SELECT = '${REVIEW_SELECT_MESSAGE}';`,
  `  var OPEN = '${REVIEW_OPEN_PIN_MESSAGE}';`,
  `  var LOCATE = '${REVIEW_PIN_LOCATE_MESSAGE}';`,
  `  var UI_ATTR = '${BRIDGE_ATTR}';`,
  '',
  '  var picking = false;',
  '  var hovered = null;',
  '  var box = null;',
  '  var chip = null;',
  '  var pinLayer = null;',
  '  var pinTip = null;',
  '  var hoveredPinId = null;',
  '  var pinTipHideTimer = null;',
  '  var pins = [];',
  '',
  '  function clamp01(v) {',
  '    return Math.max(0, Math.min(1, v));',
  '  }',
  '',
  '  function cssEscape(value) {',
  "    if (typeof CSS !== 'undefined' && typeof CSS.escape === 'function') {",
  '      return CSS.escape(value);',
  '    }',
  "    return String(value).replace(/[^a-zA-Z0-9_-]/g, '\\\\$&');",
  '  }',
  '',
  '  function isChrome(node) {',
  '    var el = node;',
  '    while (el && el.nodeType === 1) {',
  '      if (el.getAttribute && el.getAttribute(UI_ATTR) !== null) { return true; }',
  '      el = el.parentElement;',
  '    }',
  '    return false;',
  '  }',
  '',
  '  function textOf(element) {',
  "    var text = (element.textContent || '').replace(/\\s+/g, ' ').replace(/^\\s+|\\s+$/g, '');",
  "    return text.length > 80 ? text.slice(0, 80) + '\\u2026' : text;",
  '  }',
  '',
  '  function describe(element) {',
  '    var out = element.tagName.toLowerCase();',
  '    if (element.id) { out += "#" + element.id; }',
  '    else if (element.classList && element.classList.length) {',
  "      out += '.' + Array.prototype.slice.call(element.classList, 0, 3).join('.');",
  '    }',
  '    var text = textOf(element);',
  "    return text ? out + ' \"' + text + '\"' : out;",
  '  }',
  '',
  '  function selectorFor(element) {',
  '    var parts = [];',
  '    var node = element;',
  '    while (node && node.nodeType === 1 && node !== document.body) {',
  '      if (node.id) {',
  "        parts.unshift('#' + cssEscape(node.id));",
  '        break;',
  '      }',
  '      var part = node.tagName.toLowerCase();',
  '      if (node.classList && node.classList.length) {',
  "        part += '.' + Array.prototype.slice.call(node.classList, 0, 2).join('.');",
  '      }',
  '      var parent = node.parentElement;',
  '      if (parent) {',
  '        var twins = Array.prototype.filter.call(parent.children, function (child) {',
  '          return child.tagName === node.tagName;',
  '        });',
  '        if (twins.length > 1) {',
  "          part += ':nth-of-type(' + (twins.indexOf(node) + 1) + ')';",
  '        }',
  '      }',
  '      parts.unshift(part);',
  '      node = parent;',
  '    }',
  '    for (var start = parts.length - 1; start >= 0; start--) {',
  "      var candidate = parts.slice(start).join(' > ');",
  '      try {',
  '        var matches = document.querySelectorAll(candidate);',
  '        if (matches.length === 1 && matches[0] === element) { return candidate; }',
  '      } catch (error) {}',
  '    }',
  "    return parts.join(' > ');",
  '  }',
  '',
  '  function outline() {',
  '    if (box) { return box; }',
  "    box = document.createElement('div');",
  '    box.setAttribute(UI_ATTR, "");',
  "    box.style.cssText = 'position:fixed;pointer-events:none;z-index:2147483646;display:none;border:2px solid #4f46e5;background:rgba(79,70,229,0.12);box-sizing:border-box;';",
  '    document.documentElement.appendChild(box);',
  '    return box;',
  '  }',
  '',
  '  function label() {',
  '    if (chip) { return chip; }',
  "    chip = document.createElement('div');",
  '    chip.setAttribute(UI_ATTR, "");',
  "    chip.style.cssText = 'position:fixed;pointer-events:none;z-index:2147483647;display:none;background:#0f172a;color:#fff;font:11px/1.3 ui-sans-serif,system-ui,sans-serif;padding:3px 8px;border-radius:999px;white-space:nowrap;max-width:240px;overflow:hidden;text-overflow:ellipsis;';",
  '    document.documentElement.appendChild(chip);',
  '    return chip;',
  '  }',
  '',
  '  function paint(element) {',
  '    var node = outline();',
  '    var tag = label();',
  "    if (!element) { node.style.display = 'none'; tag.style.display = 'none'; return; }",
  '    var rect = element.getBoundingClientRect();',
  "    node.style.display = 'block';",
  "    node.style.left = rect.left + 'px';",
  "    node.style.top = rect.top + 'px';",
  "    node.style.width = Math.max(0, rect.width) + 'px';",
  "    node.style.height = Math.max(0, rect.height) + 'px';",
  '    tag.textContent = describe(element);',
  "    tag.style.display = 'block';",
  '    var top = rect.top - 22;',
  "    tag.style.left = Math.max(8, rect.left) + 'px';",
  "    tag.style.top = (top < 8 ? rect.bottom + 4 : top) + 'px';",
  '  }',
  '',
  '  function setPicking(next) {',
  '    picking = next;',
  '    hovered = null;',
  '    paint(null);',
  "    document.documentElement.style.cursor = next ? 'crosshair' : '';",
  '  }',
  '',
  '  function overflowOf(el, axis) {',
  "    var view = el.ownerDocument.defaultView;",
  '    if (!view) { return ""; }',
  "    var style = view.getComputedStyle(el);",
  "    return axis === 'y' ? style.overflowY : style.overflowX;",
  '  }',
  '',
  '  function canOverflow(value) {',
  "    return value === 'auto' || value === 'scroll' || value === 'overlay';",
  '  }',
  '',
  '  function wouldScroll(el, dx, dy) {',
  '    if (dy && canOverflow(overflowOf(el, "y")) && el.scrollHeight > el.clientHeight + 1) {',
  '      if (dy < 0 && el.scrollTop > 0) { return true; }',
  '      if (dy > 0 && el.scrollTop + el.clientHeight < el.scrollHeight - 1) { return true; }',
  '    }',
  '    if (dx && canOverflow(overflowOf(el, "x")) && el.scrollWidth > el.clientWidth + 1) {',
  '      if (dx < 0 && el.scrollLeft > 0) { return true; }',
  '      if (dx > 0 && el.scrollLeft + el.clientWidth < el.scrollWidth - 1) { return true; }',
  '    }',
  '    return false;',
  '  }',
  '',
  '  function onWheel(event) {',
  '    var node = event.target;',
  '    if (node && node.nodeType !== 1) { node = node.parentElement; }',
  '    while (node && node.nodeType === 1) {',
  '      if (wouldScroll(node, event.deltaX, event.deltaY)) { return; }',
  '      node = node.parentElement;',
  '    }',
  '    var root = document.scrollingElement;',
  '    if (root && wouldScroll(root, event.deltaX, event.deltaY)) { return; }',
  '    event.preventDefault();',
  '    parent.postMessage({ type: WHEEL, deltaX: event.deltaX, deltaY: event.deltaY }, "*");',
  '  }',
  '',
  '  function findPinElement(pin) {',
  '    var matches = [];',
  '    if (pin.selector) {',
  '      try { matches = Array.prototype.slice.call(document.querySelectorAll(pin.selector)); }',
  '      catch (e) { matches = []; }',
  '    }',
  '    var needle = pin.text ? String(pin.text).replace(/\\s+/g, " ").replace(/^\\s+|\\s+$/g, "").toLowerCase() : "";',
  '    if (needle && (matches.length === 0 || matches.length > 1)) {',
  '      var textMatches = matches.filter(function (m) {',
  '        return (m.textContent || "").replace(/\\s+/g, " ").toLowerCase().indexOf(needle) !== -1;',
  '      });',
  '      if (textMatches.length === 1) { return textMatches[0]; }',
  '      if (textMatches.length > 1) { matches = textMatches; }',
  '      if (matches.length === 0) {',
  '        var tagged = document.querySelectorAll("h1,h2,h3,h4,h5,h6,p,span,a,button,li,td,th,label");',
  '        var exact = Array.prototype.filter.call(tagged, function (el) {',
  '          return (el.textContent || "").replace(/\\s+/g, " ").replace(/^\\s+|\\s+$/g, "").toLowerCase() === needle;',
  '        });',
  '        if (exact.length === 1) { return exact[0]; }',
  '        if (exact.length > 1) { matches = exact; }',
  '      }',
  '    }',
  '    if (matches.length === 0) { return null; }',
  '    if (matches.length === 1) { return matches[0]; }',
  '    var fallbackX = ((pin.xPercent || 0) / 100) * Math.max(document.documentElement.scrollWidth, 1);',
  '    var fallbackY = ((pin.yPercent || 0) / 100) * Math.max(document.documentElement.scrollHeight, 1);',
  '    var best = matches[0];',
  '    var bestDist = Infinity;',
  '    for (var i = 0; i < matches.length; i++) {',
  '      var r = matches[i].getBoundingClientRect();',
  '      var cx = r.left + r.width / 2 + (window.scrollX || 0);',
  '      var cy = r.top + r.height / 2 + (window.scrollY || 0);',
  '      var dist = Math.hypot(cx - fallbackX, cy - fallbackY);',
  '      if (dist < bestDist) { bestDist = dist; best = matches[i]; }',
  '    }',
  '    return best;',
  '  }',
  '',
  '  function pinPoint(pin) {',
  '    var el = findPinElement(pin);',
  '    if (el) {',
  '      var rect = el.getBoundingClientRect();',
  '      if (!rect.width && !rect.height) { return null; }',
  '      var ax = typeof pin.anchorX === "number" ? pin.anchorX : 0.5;',
  '      var ay = typeof pin.anchorY === "number" ? pin.anchorY : 0.5;',
  '      return { left: rect.left + rect.width * ax, top: rect.top + rect.height * ay, el: el };',
  '    }',
  '    var width = Math.max(document.documentElement.scrollWidth, document.body ? document.body.scrollWidth : 0, 1);',
  '    var height = Math.max(document.documentElement.scrollHeight, document.body ? document.body.scrollHeight : 0, 1);',
  '    return {',
  '      left: ((pin.xPercent || 0) / 100) * width - (window.scrollX || 0),',
  '      top: ((pin.yPercent || 0) / 100) * height - (window.scrollY || 0),',
  '      el: null',
  '    };',
  '  }',
  '',
  '  function pinColor(pin) {',
  '    if (pin.pending) { return "#4f46e5"; }',
  '    if (pin.tone === "resolved") { return "#059669"; }',
  '    if (pin.tone === "critical") { return "#e11d48"; }',
  '    if (pin.tone === "high") { return "#f97316"; }',
  '    return "#0f172a";',
  '  }',
  '',
  '  function ensurePinLayer() {',
  '    if (pinLayer) { return pinLayer; }',
  '    var style = document.createElement("style");',
  '    style.setAttribute(UI_ATTR, "");',
  "    style.textContent = '@keyframes review-bridge-bounce{0%,100%{transform:translate(-50%,-50%)}50%{transform:translate(-50%,calc(-50% - 6px))}}';",
  '    document.documentElement.appendChild(style);',
  "    pinLayer = document.createElement('div');",
  '    pinLayer.setAttribute(UI_ATTR, "");',
  "    pinLayer.style.cssText = 'position:fixed;inset:0;pointer-events:none;z-index:2147483645;';",
  '    document.body.appendChild(pinLayer);',
  '    return pinLayer;',
  '  }',
  '',
  '  function ensurePinTip() {',
  '    if (pinTip) { return pinTip; }',
  "    pinTip = document.createElement('div');",
  '    pinTip.setAttribute(UI_ATTR, "");',
  "    pinTip.style.cssText = 'position:fixed;z-index:2147483647;display:none;width:16rem;box-sizing:border-box;padding:0.75rem;background:#0f172a;color:#f8fafc;font:12px/1.4 ui-sans-serif,system-ui,sans-serif;border:1px solid #334155;border-radius:12px;pointer-events:auto;cursor:pointer;';",
  '    pinTip.addEventListener("mouseenter", cancelPinTipHide);',
  '    pinTip.addEventListener("mouseleave", schedulePinTipHide);',
  '    pinTip.addEventListener("click", function (event) {',
  '      event.preventDefault();',
  '      event.stopPropagation();',
  '      if (hoveredPinId) { parent.postMessage({ type: OPEN, id: hoveredPinId }, "*"); }',
  '    });',
  '    document.documentElement.appendChild(pinTip);',
  '    return pinTip;',
  '  }',
  '',
  '  function cancelPinTipHide() {',
  '    if (pinTipHideTimer) { clearTimeout(pinTipHideTimer); pinTipHideTimer = null; }',
  '  }',
  '',
  '  function hidePinTip() {',
  '    cancelPinTipHide();',
  '    if (pinTip) { pinTip.style.display = "none"; }',
  '  }',
  '',
  '  function schedulePinTipHide() {',
  '    cancelPinTipHide();',
  '    pinTipHideTimer = setTimeout(function () {',
  '      hoveredPinId = null;',
  '      hidePinTip();',
  '    }, 200);',
  '  }',
  '',
  '  function statusDot(status) {',
  '    if (status === "resolved") { return "#34d399"; }',
  '    if (status === "in_progress") { return "#fbbf24"; }',
  '    return "#64748b";',
  '  }',
  '',
  '  function statusLabel(status) {',
  '    var raw = String(status || "open").replace(/_/g, " ");',
  '    return raw.charAt(0).toUpperCase() + raw.slice(1);',
  '  }',
  '',
  '  function categoryStyle(category) {',
  '    if (category === "bug") { return "background:rgba(244,63,94,0.2);color:#fda4af;border:1px solid rgba(244,63,94,0.3)"; }',
  '    if (category === "design") { return "background:rgba(99,102,241,0.2);color:#a5b4fc;border:1px solid rgba(99,102,241,0.3)"; }',
  '    if (category === "copy") { return "background:rgba(245,158,11,0.2);color:#fcd34d;border:1px solid rgba(245,158,11,0.3)"; }',
  '    return "background:#1e293b;color:#cbd5e1;border:1px solid #334155";',
  '  }',
  '',
  '  function showPinTip(point, pin) {',
  '    if (!pin || pin.pending) { hidePinTip(); return; }',
  '    cancelPinTipHide();',
  '    var tip = ensurePinTip();',
  "    tip.textContent = '';",
  "    var head = document.createElement('div');",
  "    head.style.cssText = 'display:flex;align-items:center;justify-content:space-between;gap:8px;margin:0 0 6px;padding:0 0 6px;border-bottom:1px solid #1e293b;';",
  "    var who = document.createElement('div');",
  "    who.style.cssText = 'display:flex;align-items:center;gap:6px;min-width:0;';",
  "    var num = document.createElement('span');",
  "    num.style.cssText = 'flex:none;width:20px;height:20px;border-radius:999px;background:#4f46e5;color:#fff;font:700 10px/20px ui-sans-serif,system-ui,sans-serif;text-align:center;';",
  "    num.textContent = pin.label ? '#' + pin.label : '#';",
  '    who.appendChild(num);',
  "    var name = document.createElement('span');",
  "    name.style.cssText = 'font-weight:700;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;';",
  '    name.textContent = pin.author || "";',
  '    who.appendChild(name);',
  '    head.appendChild(who);',
  '    if (pin.category) {',
  "      var cat = document.createElement('span');",
  "      cat.style.cssText = 'flex:none;padding:2px 8px;border-radius:999px;font:700 10px/1.2 ui-sans-serif,system-ui,sans-serif;text-transform:uppercase;letter-spacing:0.04em;' + categoryStyle(pin.category);",
  '      cat.textContent = pin.category;',
  '      head.appendChild(cat);',
  '    }',
  '    tip.appendChild(head);',
  "    var body = document.createElement('div');",
  "    body.style.cssText = 'color:#e2e8f0;display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:3;overflow:hidden;';",
  '    body.textContent = pin.body || "";',
  '    tip.appendChild(body);',
  "    var foot = document.createElement('div');",
  "    foot.style.cssText = 'display:flex;align-items:center;justify-content:space-between;gap:8px;margin:8px 0 0;padding:6px 0 0;border-top:1px solid #1e293b;';",
  "    var st = document.createElement('span');",
  "    st.style.cssText = 'display:inline-flex;align-items:center;gap:5px;color:#94a3b8;font:500 10px/1 ui-sans-serif,system-ui,sans-serif;';",
  "    var dot = document.createElement('span');",
  "    dot.style.cssText = 'width:6px;height:6px;border-radius:999px;background:' + statusDot(pin.status) + ';';",
  '    st.appendChild(dot);',
  "    var stLabel = document.createElement('span');",
  '    stLabel.textContent = statusLabel(pin.status);',
  '    st.appendChild(stLabel);',
  '    foot.appendChild(st);',
  "    var cta = document.createElement('span');",
  "    cta.style.cssText = 'color:#c7d2fe;font:600 11px/1 ui-sans-serif,system-ui,sans-serif;';",
  "    cta.textContent = 'Open comment';",
  '    foot.appendChild(cta);',
  '    tip.appendChild(foot);',
  "    tip.style.display = 'block';",
  '    var vw = window.innerWidth || 360;',
  '    var vh = window.innerHeight || 360;',
  '    var nearTop = point.top / vh < 0.22;',
  '    var nearRight = point.left / vw > 0.7;',
  '    var nearLeft = point.left / vw < 0.25;',
  '    var transform = nearTop',
  "      ? (nearRight ? 'translate(-100%, 4px)' : nearLeft ? 'translate(0, 4px)' : 'translate(-50%, 4px)')",
  "      : (nearRight ? 'translate(-100%, calc(-100% - 4px))' : nearLeft ? 'translate(0, calc(-100% - 4px))' : 'translate(-50%, calc(-100% - 4px))');",
  "    tip.style.left = Math.round(point.left) + 'px';",
  "    tip.style.top = Math.round(point.top) + 'px';",
  '    tip.style.transform = transform;',
  '    var box = tip.getBoundingClientRect();',
  '    var dx = 0;',
  '    var dy = 0;',
  '    if (box.left < 8) { dx = 8 - box.left; }',
  '    if (box.right > vw - 8) { dx += (vw - 8) - box.right; }',
  '    if (box.top < 8) { dy = 8 - box.top; }',
  '    if (box.bottom > vh - 8) { dy += (vh - 8) - box.bottom; }',
  '    if (dx || dy) {',
  "      tip.style.left = Math.round(point.left + dx) + 'px';",
  "      tip.style.top = Math.round(point.top + dy) + 'px';",
  '    }',
  '  }',
  '',
  '  function paintPins() {',
  '    var layer = ensurePinLayer();',
  "    layer.textContent = '';",
  '    var restored = null;',
  '    for (var i = 0; i < pins.length; i++) {',
  '      var pin = pins[i];',
  '      var point = pinPoint(pin);',
  '      if (!point) { continue; }',
  "      var btn = document.createElement('button');",
  '      btn.type = "button";',
  '      btn.setAttribute(UI_ATTR, "");',
  '      btn.textContent = pin.label || String(i + 1);',
  '      if (pin.author || pin.body) {',
  "        btn.setAttribute('aria-label', (pin.author ? pin.author + ': ' : '') + (pin.body || 'Comment'));",
  '      }',
  '      var size = pin.pending ? 32 : 28;',
  '      var ring = pin.selected ? "0 0 0 3px #818cf8,0 0 0 1px #fff" : (pin.pending ? "0 0 0 4px rgba(165,180,252,0.9)" : "0 0 0 2px #fff");',
  "      btn.style.cssText = 'position:fixed;pointer-events:auto;left:' + Math.round(point.left) + 'px;top:' + Math.round(point.top) + 'px;width:' + size + 'px;height:' + size + 'px;margin:0;padding:0;border:0;border-radius:999px;background:' + pinColor(pin) + ';color:#fff;font:700 12px/1 ui-sans-serif,system-ui,sans-serif;cursor:pointer;transform:translate(-50%,-50%);box-shadow:' + ring + ';' + (pin.pending ? 'animation:review-bridge-bounce 0.8s ease-in-out infinite;' : '');",
  '      if (!pin.pending) {',
  '        (function (marker, origin) {',
  '          btn.addEventListener("click", function (event) {',
  '            event.preventDefault();',
  '            event.stopPropagation();',
  '            parent.postMessage({ type: OPEN, id: marker.id }, "*");',
  '          });',
  '          btn.addEventListener("mouseenter", function () {',
  '            hoveredPinId = marker.id;',
  '            showPinTip(origin, marker);',
  '          });',
  '          btn.addEventListener("mouseleave", function () {',
  '            if (hoveredPinId === marker.id) { schedulePinTipHide(); }',
  '          });',
  '        })(pin, point);',
  '      }',
  '      layer.appendChild(btn);',
  '      if (hoveredPinId && pin.id === hoveredPinId) { restored = { point: point, pin: pin }; }',
  '    }',
  '    if (restored) { showPinTip(restored.point, restored.pin); }',
  '    else if (!hoveredPinId) { hidePinTip(); }',
  '  }',
  '',
  '  function locatePin(id) {',
  '    for (var i = 0; i < pins.length; i++) {',
  '      if (pins[i].id !== id) { continue; }',
  '      var point = pinPoint(pins[i]);',
  '      if (!point) { return; }',
  '      if (point.el && point.el.scrollIntoView) {',
  '        point.el.scrollIntoView({ block: "center", inline: "nearest" });',
  '        point = pinPoint(pins[i]) || point;',
  '      }',
  '      parent.postMessage({ type: LOCATE, id: id, y: point.top + (window.scrollY || 0) }, "*");',
  '      return;',
  '    }',
  '  }',
  '',
  '  function onMove(event) {',
  '    if (!picking) { return; }',
  '    var element = event.target;',
  '    if (!element || element.nodeType !== 1 || isChrome(element)) { return; }',
  '    if (element === hovered) { return; }',
  '    hovered = element;',
  '    paint(element === document.documentElement || element === document.body ? null : element);',
  '  }',
  '',
  '  function onClick(event) {',
  '    if (!picking) { return; }',
  '    var element = event.target;',
  '    if (!element || element.nodeType !== 1) { return; }',
  '    if (isChrome(element)) { return; }',
  '    event.preventDefault();',
  '    event.stopPropagation();',
  '    if (element === document.documentElement || element === document.body) { return; }',
  '    var rect = element.getBoundingClientRect();',
  '    var docEl = document.documentElement;',
  '    var scrollX = window.scrollX || docEl.scrollLeft || 0;',
  '    var scrollY = window.scrollY || docEl.scrollTop || 0;',
  '    var width = Math.max(docEl.scrollWidth, document.body ? document.body.scrollWidth : 0, 1);',
  '    var height = Math.max(docEl.scrollHeight, document.body ? document.body.scrollHeight : 0, 1);',
  '    var x = event.clientX + scrollX;',
  '    var y = event.clientY + scrollY;',
  '    parent.postMessage({',
  '      type: PICK,',
  '      target: {',
  '        selector: selectorFor(element),',
  '        describe: describe(element),',
  '        text: textOf(element),',
  '        anchorX: rect.width > 0 ? clamp01((event.clientX - rect.left) / rect.width) : 0.5,',
  '        anchorY: rect.height > 0 ? clamp01((event.clientY - rect.top) / rect.height) : 0.5,',
  '        xPercent: clamp01(x / width) * 100,',
  '        yPercent: clamp01(y / height) * 100',
  '      }',
  '    }, "*");',
  '  }',
  '',
  '  function onKeyDown(event) {',
  "    if (picking && event.key === 'Escape') {",
  '      setPicking(false);',
  '      parent.postMessage({ type: CANCEL }, "*");',
  '    }',
  '  }',
  '',
  '  function onScroll() {',
  '    if (picking && hovered) { paint(hovered); }',
  '    paintPins();',
  '  }',
  '',
  '  window.addEventListener("message", function (event) {',
  '    var data = event.data;',
  '    if (!data) { return; }',
  '    if (data.type === MODE) { setPicking(!!data.active); return; }',
  '    if (data.type === PINS) {',
  '      pins = Array.isArray(data.pins) ? data.pins : [];',
  '      paintPins();',
  '      return;',
  '    }',
  '    if (data.type === SELECT && data.id) { locatePin(data.id); }',
  '  });',
  '',
  '  document.addEventListener("mousemove", onMove, true);',
  '  document.addEventListener("click", onClick, true);',
  '  document.addEventListener("keydown", onKeyDown, true);',
  '  document.addEventListener("wheel", onWheel, { capture: true, passive: false });',
  '  window.addEventListener("scroll", onScroll, true);',
  '  window.addEventListener("resize", onScroll);',
  '  if (typeof ResizeObserver !== "undefined") {',
  '    var ro = new ResizeObserver(onScroll);',
  '    if (document.documentElement) { ro.observe(document.documentElement); }',
  '    if (document.body) { ro.observe(document.body); }',
  '  }',
  '})();',
].join('\n');

export function injectReviewBridge(html: string): string {
  if (html.includes(` ${BRIDGE_ATTR}`) || html.includes(`${BRIDGE_ATTR}=`)) {
    return html;
  }
  const snippet = `\n<script ${BRIDGE_ATTR}>${REVIEW_SCRIPT}</script>\n`;
  const closing = html.toLowerCase().lastIndexOf('</body>');
  if (closing === -1) {
    return html + snippet;
  }
  return html.slice(0, closing) + snippet + html.slice(closing);
}

function asFiniteNumber(value: unknown, fallback = 0): number {
  return typeof value === 'number' && Number.isFinite(value) ? value : fallback;
}

export function placementFromPick(raw: unknown): PinPlacement | null {
  if (!raw || typeof raw !== 'object') return null;
  const target = raw as Record<string, unknown>;
  const selector = typeof target.selector === 'string' ? target.selector.trim() : '';
  const text = typeof target.text === 'string' ? target.text.trim() : '';
  return {
    xPercent: Math.max(0, Math.min(100, asFiniteNumber(target.xPercent))),
    yPercent: Math.max(0, Math.min(100, asFiniteNumber(target.yPercent))),
    targetSelector: selector || undefined,
    targetText: text || undefined,
    anchorX: Math.max(0, Math.min(1, asFiniteNumber(target.anchorX, 0.5))),
    anchorY: Math.max(0, Math.min(1, asFiniteNumber(target.anchorY, 0.5)))
  };
}

function toneForComment(comment: CommentPin): ReviewPinTone {
  if (comment.status === 'resolved') return 'resolved';
  if (comment.priority === 'critical') return 'critical';
  if (comment.priority === 'high') return 'high';
  return 'default';
}

function clipText(value: string, max: number): string {
  const body = value.replace(/\s+/g, ' ').trim();
  return body.length > max ? `${body.slice(0, max)}…` : body;
}

export function markersFromComments(
  comments: CommentPin[],
  pending: PinPlacement | null,
  selectedId: string | null
): ReviewPinMarker[] {
  const markers: ReviewPinMarker[] = comments.map((comment) => ({
    id: comment.id,
    label: String(comment.pinNumber),
    selector: comment.targetSelector,
    text: comment.targetText,
    anchorX: comment.anchorX,
    anchorY: comment.anchorY,
    xPercent: comment.xPercent,
    yPercent: comment.yPercent,
    selected: comment.id === selectedId,
    tone: toneForComment(comment),
    author: comment.authorName,
    body: clipText(comment.content, 280),
    category: comment.category,
    status: comment.status
  }));

  if (pending) {
    markers.push({
      id: '__pending',
      label: '+',
      selector: pending.targetSelector,
      text: pending.targetText,
      anchorX: pending.anchorX,
      anchorY: pending.anchorY,
      xPercent: pending.xPercent,
      yPercent: pending.yPercent,
      pending: true
    });
  }

  return markers;
}
